### PR TITLE
Hy guys please review my work

### PR DESCRIPTION
**Pull request by NkosinathiSeptember23**

### CODE REVIEW

**Review by NompiloZondo-Dev — APPROVED** [review]
great work !

**Review by Tumisang9x — COMMENTED** [review]
Add comments to your code

**Comment by desreedimaky** [comment]
awesome job

**Review by desreedimaky — APPROVED** [review]

**Review by KevinM55 — CHANGES_REQUESTED** [review]
I see some duplicate code on line 73 please check that

**Review by Tumisang9x — APPROVED** [review]

**Review by KevinM55 — APPROVED** [review]

**Pull request merged**
